import { constVoid, memo0, memo1, memo2, memo3, memo4, memo5, memoMany } from './function'

describe('memo0', () => {
	it('caches forever', () => {
		const f = jest.fn(constVoid)
		const mf = memo0(f)
		mf()
		mf()
		expect(f).toHaveBeenCalledTimes(1)
	})
})

describe('memo1', () => {
	it('caches until argument is updated', () => {
		const f: (argument: unknown) => void = jest.fn(constVoid)
		const memo = memo1(f)
		memo(123)
		memo(123)
		expect(f).toHaveBeenCalledTimes(1)
		memo(456)
		memo(456)
		expect(f).toHaveBeenCalledTimes(2)
	})
})

describe('memo2', () => {
	it('caches until one of arguments is updated', () => {
		const f: (argument1: unknown, argument2: unknown) => void = jest.fn(constVoid)
		const memo = memo2(f)
		memo(0, 0)
		memo(0, 0)
		expect(f).toHaveBeenCalledTimes(1)
		memo(0, 1)
		memo(0, 1)
		expect(f).toHaveBeenCalledTimes(2)
		memo(1, 1)
		memo(1, 1)
		expect(f).toHaveBeenCalledTimes(3)
	})
})

describe('memo3', () => {
	it('caches until one of arguments is updated', () => {
		const f: (a: unknown, b: unknown, c: unknown) => void = jest.fn(constVoid)
		const mf = memo3(f)
		mf(0, 0, 0)
		mf(0, 0, 0)
		expect(f).toHaveBeenCalledTimes(1)
		mf(0, 0, 1)
		mf(0, 0, 1)
		expect(f).toHaveBeenCalledTimes(2)
		mf(0, 1, 0)
		mf(0, 1, 0)
		expect(f).toHaveBeenCalledTimes(3)
		mf(1, 0, 0)
		mf(1, 0, 0)
		expect(f).toHaveBeenCalledTimes(4)
	})
})

describe('memo4', () => {
	it('caches until one of arguments is updated', () => {
		const f: (a: unknown, b: unknown, c: unknown, d: unknown) => void = jest.fn(constVoid)
		const mf = memo4(f)
		mf(0, 0, 0, 0)
		mf(0, 0, 0, 0)
		expect(f).toHaveBeenCalledTimes(1)
		mf(0, 0, 0, 1)
		mf(0, 0, 0, 1)
		expect(f).toHaveBeenCalledTimes(2)
		mf(0, 0, 1, 0)
		mf(0, 0, 1, 0)
		expect(f).toHaveBeenCalledTimes(3)
		mf(0, 1, 0, 0)
		mf(0, 1, 0, 0)
		expect(f).toHaveBeenCalledTimes(4)
		mf(1, 0, 0, 0)
		mf(1, 0, 0, 0)
		expect(f).toHaveBeenCalledTimes(5)
	})
})

describe('memo5', () => {
	it('caches until one of arguments is updated', () => {
		const f: (a: unknown, b: unknown, c: unknown, d: unknown, e: unknown) => void = jest.fn(constVoid)
		const mf = memo5(f)
		mf(0, 0, 0, 0, 0)
		mf(0, 0, 0, 0, 0)
		expect(f).toHaveBeenCalledTimes(1)
		mf(0, 0, 0, 0, 1)
		mf(0, 0, 0, 0, 1)
		expect(f).toHaveBeenCalledTimes(2)
		mf(0, 0, 0, 1, 0)
		mf(0, 0, 0, 1, 0)
		expect(f).toHaveBeenCalledTimes(3)
		mf(0, 0, 1, 0, 0)
		mf(0, 0, 1, 0, 0)
		expect(f).toHaveBeenCalledTimes(4)
		mf(0, 1, 0, 0, 0)
		mf(0, 1, 0, 0, 0)
		expect(f).toHaveBeenCalledTimes(5)
		mf(1, 0, 0, 0, 0)
		mf(1, 0, 0, 0, 0)
		expect(f).toHaveBeenCalledTimes(6)
	})
})

describe('constVoid', () => {
	it('always returns undefined', () => {
		expect(constVoid()).toBeUndefined()
	})
})

describe('memoMany', () => {
	it('caches untils one of arguments is updated', () => {
		const f: (...args: readonly unknown[]) => void = jest.fn(constVoid)
		const memo = memoMany(f)
		memo(0, 0)
		expect(f).toHaveBeenCalledTimes(1)
		memo(0, 0)
		expect(f).toHaveBeenCalledTimes(1)
		memo(0, 1)
		expect(f).toHaveBeenCalledTimes(2)
		memo(0, 1)
		expect(f).toHaveBeenCalledTimes(2)
		memo(1, 1)
		expect(f).toHaveBeenCalledTimes(3)
		memo(1, 1)
		expect(f).toHaveBeenCalledTimes(3)
	})
	it('returns cached value immediately for 0 arguments', () => {
		const f = jest.fn(constVoid)
		const memo = memoMany(f)
		memo()
		expect(f).toHaveBeenCalledTimes(1)
		memo()
		expect(f).toHaveBeenCalledTimes(1)
	})
	it('resets cache when number of arguments drops zero', () => {
		const f = jest.fn((...args: readonly unknown[]): number => args.length)
		const memo = memoMany(f)
		expect(memo(1)).toEqual(1)
		expect(memo(1)).toEqual(1)
		expect(memo()).toEqual(0)
	})
})
