name: Build

on:
  push:
    branches-ignore:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NODE_VERSION: 14

    # Checkout code
    steps:
      - uses: actions/checkout@v2

      # Setup node
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      # Cache node_modules
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-v${{ env.NODE_VERSION }}-${{ hashFiles('**/yarn.lock') }}

      # Commitlint
      - run: npx commitlint --from HEAD~1 --to HEAD --verbose

      # Install dependencies
      - run: yarn install --frozen-lockfile

      # Typecheck
      - run: yarn typecheck

      # Build
      - run: yarn build

      # Test
      - run: yarn test
