name: Build

on:
  push:
    branches-ignore:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NODE_VERSION: 14

    # Checkout code
    steps:
      - uses: actions/checkout@v2
        with:
          # we actually need "github.event.pull_request.commits + 1" commit
          fetch-depth: 0

      # Setup node
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      # Cache node_modules
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-v${{ env.NODE_VERSION }}-${{ hashFiles('**/yarn.lock') }}

      # Install dependencies
      - run: yarn install --frozen-lockfile

      # Lint
      - run: npx commitlint --from HEAD~${{ github.event.pull_request.commits }} --to HEAD --verbose

      # Build
      - run: yarn build

      # Typecheck
      - run: yarn typecheck

      # Test
      - run: yarn test
